// <auto-generated />
using System;
using ExcelAutomation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelAutomation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116113735_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("ExcelAutomation.Models.SalesHistory", b =>
                {
                    b.Property<DateTime>("SalesDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("sales_date");

                    b.Property<string>("ProductCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_price");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_by");

                    b.HasKey("SalesDate", "ProductCode");

                    b.ToTable("SalesHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
